### ISSUE TITLE
Add the css style to the html code

### ISSUE THREAD

**Issue by mfaridzia** [mfaridzia/counter-hack-app#1]
### **Description**
Adding the css style to the html code that was created, it is better to use CSS Flexbox or CSS Grid to give style to the page.

### Note:
- Save the css code into the _style.css_ file
- Don't use the css framework, it's better to use pure css

**Comment by nir099** [comment]
took this one XD

**Comment by dpritos** [comment]
#11

**Comment by lemuellloren** [comment]
Css style to the html code that was created

**Comment by Myles2** [comment]
@mfaridzia I'm new to open source projects but if this is still open I would like to give it a try!
