### ISSUE TITLE
Add a javascript code to make the counter function run

### ISSUE THREAD

**Issue by mfaridzia** [mfaridzia/counter-hack-app#2]
### **Description**
Add javascript code to make the counter function run properly

##### **Note:**
Add the javascript code to the main.js file

**Comment by Aniket-Pradhan** [comment]
You just need a counter? Like a for loop, and done?

if that's that, then I'll do it. :3

**Comment by SasiniSithara** [comment]
https://github.com/mfaridzia/counter-hack-app/labels/hacktoberfest

**Comment by joshuaGlass808** [comment]
#7
